### ISSUE TITLE
Multiprocessing does not work 

### ISSUE THREAD

**Issue by sbuschjaeger** [adaptive-machine-learning/CapyMOA#195]
CapyMoa does not work well in (python-based) multi-threaded environments. According to jpype, multi-threading via `spawn` instead of `fork` should generally be working (see also https://jpype.readthedocs.io/en/latest/userguide.html#multiprocessing). However, the following minimal example gives a bunch of RuntimeErrors:

```python
#!/usr/bin/env python3
import argparse
import multiprocessing
import os
from capymoa.classifier._hoeffding_tree import HoeffdingTree
from capymoa.datasets._datasets import ElectricityTiny
from capymoa.evaluation.evaluation import ClassificationEvaluator
import pandas as pd
import tqdm

def run_experiment(args):
    # Run a single experiment with the given arguments
    grace_period, confidence, leaf_prediction = args
    stream = ElectricityTiny()
    evaluator = ClassificationEvaluator(schema=stream.get_schema())
    model = HoeffdingTree(schema=stream.get_schema(), grace_period=grace_period, confidence=confidence, leaf_prediction=leaf_prediction)

    while stream.has_more_instances():
        instance = stream.next_instance()
        prediction = model.predict(instance)
        evaluator.update(instance.y_index, prediction)
        model.train(instance)

    df = pd.DataFrame({"grace_period":grace_period, "confidence":confidence, "leaf_prediction": leaf_prediction, "accuracy":[evaluator.accuracy()], "kappa":[evaluator.kappa()], "kappa_t":[evaluator.kappa_t()], "kappa_m":[evaluator.kappa_m()], "f1_score": [evaluator.f1_score()], "precision":[evaluator.precision()], "recall":[evaluator.recall()]})
    return df

def main(args):
    # Generate a few different configurations of HoeffdingTrees so we actually have something to run in parallel
    models = []
    for g in [50, 100, 250]:
        for c in [0.1,0.01,0.001]:
            for p in ["MajorityClass", "NaiveBayes"]:
                models.append((g, c, p))

    print(f"Generated {len(models)} configs.")
    if args.n_jobs > 1:
        with multiprocessing.get_context("spawn").Pool(args.n_jobs, maxtasksperchild=1) as pool:
            with open(os.path.join("results.csv"), 'a') as f:
                for df in tqdm.tqdm(pool.imap_unordered(run_experiment, models), total=len(models)):
                    if df is not None:
                        df.to_csv(f, header=f.tell()==0, index=False)
    else:
        with open(os.path.join("results.csv"), 'a') as f:
            for m in tqdm.tqdm(models, total=len(models)):
                df = run_experiment(m)
                if df is not None:
                    df.to_csv(f, header=f.tell()==0, index=False)  

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-j", "--n_jobs", help="Number of jobs for processing pool",type=int, default=1)
    args = parser.parse_args()

    main(args)
```

Funnily, the code seems to work as intendent (all experiments finish on my machine) and only at the very end I recieve import errors such as: 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/projects/CapyMOA/test_multiprocessing.py", line 5, in <module>
    from capymoa.classifier._hoeffding_tree import HoeffdingTree
  File "/root/projects/CapyMOA/src/capymoa/__init__.py", line 9, in <module>
    from . import stream
  File "/root/projects/CapyMOA/src/capymoa/stream/__init__.py", line 3, in <module>
    from . import drift, generator, preprocessing
  File "/root/projects/CapyMOA/src/capymoa/stream/preprocessing/__init__.py", line 1, in <module>
    from .pipeline import (
  File "/root/projects/CapyMOA/src/capymoa/stream/preprocessing/pipeline.py", line 7, in <module>
    from capymoa.stream.preprocessing.transformer import Transformer
  File "/root/projects/CapyMOA/src/capymoa/stream/preprocessing/transformer.py", line 7, in <module>
    from moa.streams import FilteredQueueStream
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
RuntimeError: Unable to import 'moa.streams.FilteredQueueStream' without JVM
```

The individual errors seem to depend on the number of jobs given (they are different on my machine for `n_jobs=2` and `n_jobs=4`). I currently suspect, that jpype + torch does not work well together since I used jpype + spawn already in a few projects without any issues.

**Comment by nuwangunasekara** [comment]
@sbuschjaeger 

Thanks for reporting the issue!
I think you are correct, jpype and pytorch does not seem to go together :(

This simple patch which remove `PytorchStream` from CapyMOA seems to removes calling pytorch at-least from your example program. 


```
diff --git a/src/capymoa/stream/__init__.py b/src/capymoa/stream/__init__.py
index 7b1b117..71f281f 100644
--- a/src/capymoa/stream/__init__.py
+++ b/src/capymoa/stream/__init__.py
@@ -1,5 +1,5 @@
 from ._stream import Stream, Schema, ARFFStream, stream_from_file, CSVStream, NumpyStream
-from .PytorchStream import PytorchStream
+# from .PytorchStream import PytorchStream
 from . import drift, generator, preprocessing

 __all__ = [
@@ -7,7 +7,7 @@ __all__ = [
     "Schema",
     "stream_from_file",
     "ARFFStream",
-    "PytorchStream",
+    # "PytorchStream",
     "CSVStream",
     "drift",
     "generator",
```

But we still have to think about pytorch integration in deep.

**Comment by sbuschjaeger** [comment]
Hi @nuwangunasekara
Thanks for the patch. It does help a little (2 jobs now work) as it seems, but it does not fully fix this issue for me. For example, using `n_jobs= 4` gives me this:

```
./test_multiprocessing.py -j 4
Generated 18 configs.
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 18/18 [00:12<00:00,  1.39it/s]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00005653bf42a800, pid=89918, tid=89918
#
# JRE version: OpenJDK Runtime Environment (11.0.24+8) (build 11.0.24+8-post-Ubuntu-1ubuntu322.04)
# Java VM: OpenJDK 64-Bit Server VM (11.0.24+8-post-Ubuntu-1ubuntu322.04, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [python3+0x576800]  PyBaseObject_Type+0x0
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport -p%p -s%s -c%c -d%d -P%P -u%u -g%g -- %E" (or dumping to /root/projects/CapyMOA/core.89918)
#
# An error report file with more information is saved as:
# /root/projects/CapyMOA/hs_err_pid89918.log
#
# If you would like to submit a bug report, please visit:
#   https://bugs.launchpad.net/ubuntu/+source/openjdk-lts
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/usr/lib/python3.10/runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/root/projects/CapyMOA/test_multiprocessing.py", line 5, in <module>
    from capymoa.classifier._hoeffding_tree import HoeffdingTree
  File "/root/projects/CapyMOA/src/capymoa/classifier/__init__.py", line 10, in <module>
    from ._knn import KNN
  File "/root/projects/CapyMOA/src/capymoa/classifier/_knn.py", line 2, in <module>
    from moa.classifiers.lazy import kNN as _moa_kNN
ModuleNotFoundError: No module named 'moa.classifiers.lazy'
```

Clearly, this is not a torch-related issue. This seems to be more related to the JVM directly. If you want to, I can also add the error log (although I did not find anything helpful there). 

My guess at the moment: 
I am not 100% sure how jpype works, but I typically would use 1 JVM per thread (i.e. call `jpype.startJVM(..)` in each process after I spawned it - but I am not sure if this actually starts a new instance or just returns the one that is already running). Currently, the JVM is started during import and I suspect that one JVM instance is thus shared across all threads (I think?). Hence, it would probably be better to either manually start the JVM or to start them on-demand, but I understand that this would be a major change to the API.

**Comment by hmgomes** [comment]
Hey @sbuschjaeger , thanks for raising this. You can add a function that ensures the JVM is started in each worker process after they are spawned. jpype requires the JVM to be initialized separately in every process that needs to access MOA (java) objects, child processes created with spawn do not inherit the JVM state from the parent process. Therefore, you need to explicitly start the JVM in each child process to avoid any issues when working with Java objects in parallel.

**Comment by hmgomes** [comment]
Something like the code below, it is a quick and dirty adaptation to get it to work. Needs to investigate a better way of doing this. Notice that it requires the location of the `moa.jar`(which can be found at `/CapyMOA/src/capymoa/jar/moa.jar`)


```
import argparse
import multiprocessing
import os
from jpype import startJVM, isJVMStarted, getDefaultJVMPath
import tqdm
from pathlib import Path

# function to get the MOA jar and JVM args, must be updated to point to the moa.jar
def get_classpath_and_jvm_args():
    # Example path logic from CapyMOA
    moa_jar = Path("./CapyMOA/src/capymoa/jar/moa.jar")  # Replace with the actual path
    if not moa_jar.exists():
        raise FileNotFoundError(f"MOA JAR not found at `{moa_jar}`.")
    jvm_args = ["-Xmx4g"]
    return moa_jar, jvm_args

# JVM initialization function
def initialize_jvm():
    if not isJVMStarted():
        moa_jar, jvm_args = get_classpath_and_jvm_args()
        
        # Start JVM with the dynamically determined classpath and args
        startJVM(getDefaultJVMPath(), f"-Djava.class.path={moa_jar.as_posix()}", *jvm_args)

def run_experiment(args):
    initialize_jvm()  # inits the JVM in each process

    # Import after JVM initialization
    from capymoa.classifier._hoeffding_tree import HoeffdingTree  
    from capymoa.datasets._datasets import ElectricityTiny
    from capymoa.evaluation.evaluation import ClassificationEvaluator
    import pandas as pd

    grace_period, confidence, leaf_prediction = args
    stream = ElectricityTiny()
    evaluator = ClassificationEvaluator(schema=stream.get_schema())
    model = HoeffdingTree(schema=stream.get_schema(), grace_period=grace_period, confidence=confidence, leaf_prediction=leaf_prediction)

    while stream.has_more_instances():
        instance = stream.next_instance()
        prediction = model.predict(instance)
        evaluator.update(instance.y_index, prediction)
        model.train(instance)

    df = pd.DataFrame({
        "grace_period": grace_period,
        "confidence": confidence,
        "leaf_prediction": leaf_prediction,
        "accuracy": [evaluator.accuracy()],
        "kappa": [evaluator.kappa()],
        "kappa_t": [evaluator.kappa_t()],
        "kappa_m": [evaluator.kappa_m()],
        "f1_score": [evaluator.f1_score()],
        "precision": [evaluator.precision()],
        "recall": [evaluator.recall()]
    })
    return df

def main(args):
    models = []
    for g in [50, 100, 250]:
        for c in [0.1, 0.01, 0.001]:
            for p in ["MajorityClass", "NaiveBayes"]:
                models.append((g, c, p))

    print(f"Generated {len(models)} configs.")
    
    if args.n_jobs > 1:
        multiprocessing.set_start_method("spawn", force=True)
        with multiprocessing.Pool(args.n_jobs, maxtasksperchild=1) as pool:
            with open(os.path.join("results.csv"), 'a') as f:
                for df in tqdm.tqdm(pool.imap_unordered(run_experiment, models), total=len(models)):
                    if df is not None:
                        df.to_csv(f, header=f.tell() == 0, index=False)
    else:
        with open(os.path.join("results.csv"), 'a') as f:
            for m in tqdm.tqdm(models, total=len(models)):
                df = run_experiment(m)
                if df is not None:
                    df.to_csv(f, header=f.tell() == 0, index=False)

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("-j", "--n_jobs", help="Number of jobs for processing pool", type=int, default=4)

    args = parser.parse_args()
    main(args)

```

**Comment by sbuschjaeger** [comment]
Hi @hmgomes 
Thank you for the quick response. Unfortunately, that also does not seem to fix the issue. If I run the script multiple times in a row, a few runs fail while other runs succeed. This effect becomes more prominent the more jobs I use. One quickfix I found is to add a `time.sleep` in the beginning of each function, i.e.

```python
def run_experiment(args):
    #initialize_jvm()  # initialize_jvm is not required when using time.sleep as far as I can tell
    time.sleep(1)

    grace_period, confidence, leaf_prediction = args
    stream = ElectricityTiny()
    evaluator = ClassificationEvaluator(schema=stream.get_schema())
    model = HoeffdingTree(schema=stream.get_schema(), grace_period=grace_period, confidence=confidence, leaf_prediction=leaf_prediction)

    while stream.has_more_instances():
        instance = stream.next_instance()
        prediction = model.predict(instance)
        evaluator.update(instance.y_index, prediction)
        model.train(instance)

    df = pd.DataFrame({"grace_period":grace_period, "confidence":confidence, "leaf_prediction": leaf_prediction, "accuracy":[evaluator.accuracy()], "kappa":[evaluator.kappa()], "kappa_t":[evaluator.kappa_t()], "kappa_m":[evaluator.kappa_m()], "f1_score": [evaluator.f1_score()], "precision":[evaluator.precision()], "recall":[evaluator.recall()]})
    return df
```

This way, no errors occur, although I am not sure why.

**Comment by nuwangunasekara** [comment]
@sbuschjaeger 
Thanks for the insights!
Looks like the VM needs some time to settle in when you start them from a script, which is understandable.
Maybe you could also have a small sleep after 
`
model = HoeffdingTree(schema=stream.get_schema(), grace_period=grace_period, confidence=confidence, leaf_prediction=leaf_prediction)
`
(before you enter the loop) so that the underlying MOA stuff are properly initialized.

**Comment by hmgomes** [comment]
Hi @sbuschjaeger and @nuwangunasekara 

> This way, no errors occur, although I am not sure why.
So, now you can consistently complete all your experiments? 
I am glad that we have a workaround, now we need to understand why that happens. The following step is to document this and create an example

**Comment by nuwangunasekara** [comment]
We may also want have 'PytorchStream' as a separate module which is not built with CapyMOA. But can be used with it when Pytorch is installed.

**Comment by sbuschjaeger** [comment]
> Hi @sbuschjaeger and @nuwangunasekara
> 
> > This way, no errors occur, although I am not sure why.
> 
> So, now you can consistently complete all your experiments? I am glad that we have a workaround, now we need to understand why that happens. The following step is to document this and create an example (probably as part of [notebook 6](https://capymoa.org/notebooks/06_advanced_API.html) along other advanced topics).

I did some additional tests, and this seems to (reliably) fix the issue for me. I can submit a pull request in the next few weeks that adds this to the documentation.
